### ISSUE TITLE
camera fails to re-initialise after completing a level

### ISSUE THREAD

**Issue by aHigs** [DevdudeX/LMD-Alternative-Camera-Mod#2]
After finishing a level with alternate camera and starting a different one, 9 and 0 correctly unlock the camera, but it fails to follow the rider and stays in a single spot unless i keep holding RMB.

Understand that keypad 9 is probably needed to update references but that doesn't seem to work for me.
Also it would be great to mvoe those shortcuts from the numpad if possible

**Comment by gnagga** [comment]
yup, can confirm this is still the case unfortunately.

**Comment by gnagga** [comment]
for me it works, you just have to press 9 again after loading the new level.

**Comment by DannyU5** [comment]
I have similar problem. I am able to use the mod for one level, but after completion and starting a new one (or even restarting same one) the camera starts further out. Pressing 0 or 9 does turn the mod on, but the camera does not follow the rider, it stays "locked" in the initial position. Pressing any key bind besides 0 does nothing, and if I press 0 again, the whole game crashes.

Here is the log from start of one level:

```
[11:13:22.466] [Alternative_Camera] Starting alternative camera system!
[11:13:22.508] [Alternative_Camera] Applied a camera preset!
[11:17:39.915] [Alternative_Camera] Alternative Camera system already started!
[11:17:39.916] [Alternative_Camera] Applied a camera preset!
[11:17:39.920] [Alternative_Camera] Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.

--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at UnityEngine.Component.get_gameObject()
   at AlternativeCameraMod.AlternativeCamera.AlignViewWithBike()
   at AlternativeCameraMod.AlternativeCamera.ToggleModState()
   at AlternativeCameraMod.AlternativeCamera.OnLateUpdate()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[11:17:41.179] [Alternative_Camera] Alternative Camera system already started!
[11:17:41.180] [Alternative_Camera] Applied a camera preset!
[11:17:41.180] [Alternative_Camera] Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.

--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at UnityEngine.Component.get_gameObject()
   at AlternativeCameraMod.AlternativeCamera.AlignViewWithBike()
   at AlternativeCameraMod.AlternativeCamera.ToggleModState()
   at AlternativeCameraMod.AlternativeCamera.OnLateUpdate()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[11:17:41.201] [Alternative_Camera] Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.Transform.get_localRotation () [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at UnityEngine.Transform.get_localRotation()
   at AlternativeCameraMod.AlternativeCamera.CameraLogic()
   at AlternativeCameraMod.AlternativeCamera.OnLateUpdate()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```

And then the last part repeats like 50 times before the crash happens:
```
[11:17:41.212] [Alternative_Camera] Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.Transform.get_localRotation () [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at UnityEngine.Transform.get_localRotation()
   at AlternativeCameraMod.AlternativeCamera.CameraLogic()
   at AlternativeCameraMod.AlternativeCamera.OnLateUpdate()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```
Is this a problem with the mod, or with the melon loader and dependencies?

**Comment by aHigs** [comment]
Potentially something small with the mod - i don't get the same issue with the fork that implements camera mode:
https://github.com/faehromon/LMD-Alternative-Camera-Mod
